name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name : Install node
        run: sudo apt-get install nodejs
      - name: Install npm
        run: sudo apt-get install npm
      - name: clone sag repository
        run: git clone git@github.com:HAYASAKA-Ryosuke/sag.git
      - name: Change directory
        run: cd sag
      - name: Prepare build directory
        run: |
          mkdir public
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm
        run: wasm-pack build --target web
      - name: Copy index.html
        run: cp ../index.html public/
      - name: Copy pkg
        run: cp -r pkg public/
      - name: Upload Pages Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
