name: GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name : Install node
        run: sudo apt-get install nodejs
      - name: Install pnpm
        run: sudo apt-get install npm
      - name: Prepare build directory
        run: |
          mkdir public
          ls -ltar
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: HAYASAKA-Ryosuke/sag.git
          path: sag

      - name: Build WASM
        run: |
          cd sag
          wasm-pack build --target web
          cd ..
          cp -r sag/pkg ./

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
      - name: Upload Pages Artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
